version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/server
    overwrite: true
    exclude:
      - .git
      - .github
      - .gitignore
hooks:
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user